<a href="https://colab.research.google.com/github/gustavodgomez-2026/App-Ecommerce/blob/main/Ejercicio4(2).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Ejercicio 4 — Proyecto Final Integrador

**Módulo: Python para IA** | Máster en Inteligencia Artificial

**Tipo**: Proyecto final | **Sesión**: 4

---

## 🎯 Objetivo

Construir una **aplicación web con IA** y desplegarla online. Este proyecto integra todo lo aprendido en el módulo: Python, prompting, modelos de IA, interfaces y deployment.

No se evalúa la complejidad del código (podéis usar IA para generarlo), sino la **idea, la funcionalidad y la capacidad de llevarlo a producción**.

---
## ¿Qué tienes que construir?

Elige **una** de las tres opciones siguientes. Elige la que más te interese, no la más fácil — la motivación importa.

Todas las opciones requieren:
- Una **interfaz web** (Gradio o Streamlit)
- Un **modelo de IA** integrado (API de Gemini, HuggingFace, LangChain, etc.)
- **Deployment** online (HuggingFace Spaces o Streamlit Cloud)
- Un **repositorio GitHub** con el código

---
## Opción A — App Multi-IA con Gradio/Streamlit

Crear una aplicación que use IA generativa para **al menos 2 operaciones distintas**.

**Ejemplos de combinaciones:**
- Resumen + Traducción + Análisis de sentimiento
- Generación de texto + Clasificación + QA
- Extracción de entidades + Generación de respuestas

**¿Qué se espera?** Una interfaz donde el usuario pueda elegir entre diferentes capacidades de IA y ver los resultados. Puede organizarse con pestañas (tabs) o como una interfaz unificada.

> 🤖 **Prompt sugerido**: *"Crea una app Gradio con tabs que tenga: (1) un analizador de sentimiento con HuggingFace, (2) un resumidor de textos con Gemini, y (3) una herramienta de traducción. Cada tab tiene su propio input y output."*

---
## Opción B — Sistema RAG con Interfaz

Crear un **sistema de pregunta-respuesta sobre documentos propios**.

**Requisitos mínimos:**
- Al menos **10 documentos/fragmentos** indexados (sobre un tema que te interese)
- Al menos **3 preguntas de demo** que funcionen correctamente
- Interfaz con Gradio o Streamlit

**¿Qué se espera?** Un chatbot que responda preguntas basándose en tus documentos, no en conocimiento general. Ideal si quieres profundizar en lo aprendido en la Sesión 3 (LangChain + RAG).

> 🤖 **Prompt sugerido**: *"Crea una app Gradio con sistema RAG usando LangChain y Gemini. Los documentos son [describe tu tema]. Incluye un ChatInterface que muestre las fuentes usadas en cada respuesta."*

---
## Opción C — Agente Conversacional

Crear un **chatbot avanzado** con capacidades adicionales.

**Requisitos mínimos:**
- **Memoria**: recuerda lo dicho en la conversación
- Al menos **1 herramienta** integrada (búsqueda web, cálculo, consulta a API externa, etc.)
- Interfaz con Gradio o Streamlit

**¿Qué se espera?** Un chatbot que no solo responda preguntas, sino que pueda **hacer cosas**: buscar información actualizada, calcular, consultar datos en tiempo real. Es la opción más avanzada, pero también la más impresionante.

> 🤖 **Prompt sugerido**: *"Crea un agente con LangChain y Gemini que tenga memoria de conversación y herramientas de búsqueda web (DuckDuckGo) y calculadora. Despliégalo con Gradio ChatInterface."*

---
## ¿Cómo abordar el proyecto?

1. **Elige la opción** que más te interese y define el tema concreto de tu app.
2. **Escribe una spec**: qué hace la app, qué tecnologías usa, qué flujo sigue el usuario. Una spec clara permite pedirle a la IA que genere el código base completo.
3. **Pide a Gemini/Copilot** que genere el código a partir de la spec.
4. **Prueba en Colab o local** — haz que funcione lo básico antes de añadir más.
5. **Despliega pronto** (HuggingFace Spaces o Streamlit Cloud). No esperes al último día: un deploy inicial con la versión mínima te evita sorpresas.
6. **Itera**: prueba → mejora → vuelve a desplegar.

> 💡 **Empieza simple**: un prototipo funcional en 30 minutos vale más que un plan ambicioso que no se termina.

---
## Criterios de Evaluación

| Criterio | Peso | Descripción | Qué se valora |
|----------|:----:|-------------|---------------|
| **Funcionalidad** | 40% | La app funciona correctamente, sin errores | Que haga lo que promete. Que no se rompa con inputs inesperados. Que el flujo sea completo. |
| **Uso de IA generativa** | 25% | Integración efectiva de modelos/APIs | Que la IA aporte valor real. Uso correcto de prompts, parámetros y manejo de errores de API. |
| **UI/UX** | 15% | Interfaz clara, intuitiva y usable | Títulos claros, inputs con labels descriptivos, ejemplos de uso, feedback al usuario. |
| **Documentación** | 10% | README claro, type hints, docstrings | README con descripción, instrucciones de instalación y capturas de pantalla. |
| **Deployment** | 10% | App desplegada y accesible online | La URL funciona. Los secretos están bien gestionados (no hay API keys en el código). |

---
## Entrega

Sube en el formulario de **Blackboard** un archivo **docx** con:

- **Link al repositorio de GitHub** (debe ser público)
- **Link a la app desplegada** (HuggingFace Spaces o Streamlit Cloud)
- **Capturas de pantalla** de la app funcionando
- **Capturas del código** (las partes más relevantes)

**Archivos mínimos en el repositorio:**
```
mi-app/
├── app.py              # Código de la aplicación
├── requirements.txt    # Dependencias
└── README.md           # Descripción, instrucciones y link a la app
```

**El README.md debe incluir:**
- Descripción del proyecto (qué hace y por qué)
- Tecnologías utilizadas (Gradio/Streamlit, modelos, APIs)
- Instrucciones de instalación y ejecución local
- Link a la app desplegada
- Capturas de pantalla de la app funcionando

> ⚠️ Asegúrate de que ambos links son públicos y accesibles antes de entregar. Si la URL no funciona, la nota máxima será **30%** (solo se evalúa el código del repo).

---
## 💡 Tips

### Proceso recomendado

- **Usa prompting agresivamente**: este módulo se llama "Python para IA" — se espera que uses IA para desarrollar. Dale tu spec a Gemini y pídele que genere el proyecto completo. Itera sobre el resultado.
- **Git desde el inicio**: crea el repo de GitHub antes de empezar a codificar. Haz commits frecuentes. Así nunca pierdes trabajo y el historial documenta tu proceso.
- **Testa el deployment pronto**: haz un deploy inicial con la versión más simple posible e id actualizando. No esperes a tenerlo perfecto.

### Errores comunes a evitar

| Error | Consecuencia | Solución |
|-------|-------------|----------|
| API key en el código | Seguridad comprometida, repo bloqueado | Usar secrets de HF/Streamlit + `os.environ` |
| No testear antes del deploy | "En mi notebook funcionaba" | Probar en un entorno limpio |
| README vacío | El evaluador no sabe qué hace la app | Escribir el README antes del código |
| Ignorar errores de la API | La app se rompe cuando la API falla | `try/except` en todas las llamadas a APIs |
| Proyecto demasiado ambicioso | No se termina a tiempo | Empezar con lo mínimo funcional |

---
## 📚 Recursos

- [Gradio — Documentación](https://gradio.app/docs/)
- [Gradio — ChatInterface](https://www.gradio.app/docs/gradio/chatinterface)
- [Streamlit — Documentación](https://docs.streamlit.io/)
- [Streamlit — Cheat Sheet](https://docs.streamlit.io/develop/quick-reference/cheat-sheet)
- [HuggingFace Spaces — Crear un Space](https://huggingface.co/docs/hub/spaces-overview)
- [HuggingFace Spaces — Secrets](https://huggingface.co/docs/hub/spaces-overview#managing-secrets)
- [Streamlit Cloud — Deployment](https://docs.streamlit.io/deploy/streamlit-community-cloud)
- [Google AI — Python SDK](https://ai.google.dev/gemini-api/docs/quickstart?lang=python)

```markdown
# mi-app

## Descripción del Proyecto
Este proyecto es una aplicación web interactiva de e-commerce con IA, construida para permitir a los usuarios categorizar imágenes de productos y obtener información relevante a través de un asistente de chat impulsado por inteligencia artificial. La aplicación integra funcionalidades de clasificación de imágenes, procesamiento de lenguaje natural y una experiencia de usuario que simula la interacción en una plataforma de comercio electrónico, incluyendo la selección de productos y la adición (simulada) al carrito.

## Tecnologías Utilizadas
*   **Frontend/Interfaz:** Gradio (gr.Blocks, gr.Image, gr.Textbox, gr.Button, gr.Chatbot, gr.CheckboxGroup) para la construcción de la interfaz de usuario.
*   **Clasificación de Imágenes:** Modelos de Hugging Face Transformers (`google/vit-base-patch16-224`) para la categorización automática de imágenes de productos.
*   **Modelo de Lenguaje (LLM):** Google Gemini (`gemini-2.5-flash`) para las capacidades de conversación del chatbot.
*   **Manejo de Datos:** La librería Pandas se utiliza para la gestión y manipulación de la base de datos de productos.
*   **Entorno de Desarrollo y Despliegue:** Google Colab para el desarrollo inicial y Hugging Face Spaces / Streamlit Cloud para el despliegue online.

## Funcionalidades Clave
La aplicación se compone de los siguientes módulos principales:

### 1. Base de Datos de Productos
Una colección predefinida de productos (laptops, monitores, periféricos) con detalles como modelo, precio, stock y descripción, que sirve como fuente de información para el asistente de chat.

### 2. Módulo de Categorización de Imágenes
Permite a los usuarios subir una imagen de un producto. Un modelo de IA clasifica la imagen en una de las categorías predefinidas (`laptop`, `monitor`, `perifericos`). El usuario puede borrar la imagen o usar la categoría predicha para interactuar con el chatbot.

### 3. Asistente de Información de Productos (Chatbot)
Un asistente conversacional que interactúa con el usuario y proporciona información basada en el contexto:
*   **Respuestas Generales:** Utiliza Google Gemini para responder preguntas abiertas.
*   **Respuestas Contextualizadas:** Si una imagen ha sido categorizada, el chatbot ofrece listar los productos de esa categoría.
*   **Selección de Productos:** Presenta los modelos disponibles de una categoría en un formato seleccionable (checkboxes) y simula la adición de productos al carrito.

## Instalación y Ejecución Local

### Prerrequisitos
*   Python 3.8+
*   Clave API de Google Gemini (configurada como secreto de entorno `GEMINI_API_KEY`)

### Pasos
1.  Clona el repositorio:
    ```bash
    git clone https://github.com/tu-usuario/mi-app.git
    cd mi-app
    ```
2.  Crea un entorno virtual (recomendado):
    ```bash
    python -m venv venv
    source venv/bin/activate # En Windows usa `venv\Scripts\activate`
    ```
3.  Instala las dependencias:
    ```bash
    pip install -r requirements.txt
    ```
    (Asegúrate de que `requirements.txt` contenga `gradio==3.50.2`, `transformers`, `accelerate`, `torch`, `google-generativeai`, `pandas`)
4.  Configura tu clave API de Gemini:
    Asegúrate de tener tu `GEMINI_API_KEY` configurada como una variable de entorno. Por ejemplo:
    ```bash
    export GEMINI_API_KEY='tu_clave_aqui'
    # O si usas Colab/Hugging Face Spaces, configura como un 'Secret'.
    ```
5.  Ejecuta la aplicación:
    ```bash
    python app.py
    ```
    (Si estás en Colab, simplemente ejecuta las celdas del notebook).

## Despliegue Online

La aplicación está diseñada para ser fácilmente desplegable en plataformas como Hugging Face Spaces o Streamlit Cloud.

### Hugging Face Spaces
1.  Crea un nuevo Space en Hugging Face.
2.  Conecta tu repositorio GitHub.
3.  Asegúrate de que tu `requirements.txt` esté correcto.
4.  Configura `GEMINI_API_KEY` como un secreto de entorno en tu Space.

**Link a la App Desplegada:** [URL de tu aplicación desplegada aquí]

## Capturas de Pantalla
(Añade aquí capturas de pantalla de tu aplicación funcionando, mostrando la categorización de imágenes, la interacción del chatbot y la selección de productos).

**Ejemplo:**

![Captura de pantalla de la interfaz principal]

![Captura de pantalla de la interacción del chatbot]

```

In [17]:
%%writefile requirements.txt
gradio==3.50.2
transformers
accelerate
torch
google-generativeai
pandas
pillow

Overwriting requirements.txt

In [18]:
# Comprueba tus links antes de entregar
#repo_url = ""   # Ej: "https://github.com/tu-usuario/tu-app"
#app_url  = ""   # Ej: "https://tu-usuario-tu-app.hf.space"

#print(f"Repositorio:   {repo_url}")
#print(f"App desplegada: {app_url}")

#assert repo_url.startswith("https://github.com/"), "❌ El link del repo no parece correcto"
#assert app_url.startswith("https://"), "❌ El link de la app no parece correcto"
#print("✅ Links con formato correcto — recuerda comprobar que son públicos y accesibles")

In [19]:
# "Crea una app Gradio con tabs que tenga: (1) un analizador de sentimiento con HuggingFace, (2) un resumidor de textos con Gemini, y (3) una herramienta de traducción. Cada tab tiene su propio input y output."

### Instalación de librerías
Primero, instalaremos las librerías necesarias para la aplicación: `gradio` y `transformers` para los modelos de Hugging Face.

In [20]:
import sys

!{sys.executable} -m pip install gradio==3.50.2 transformers accelerate torch --quiet

# Para evitar advertencias de tokenizers
import os
os.environ["TOKENIZERS_PARALLELISM"] = "false"

### 1. Base de datos de E-commerce
Definiremos la base de datos de productos en un diccionario Python. Esta será la fuente de información para el chatbot.

In [21]:
ecommerce_products = [
    # Laptops
    {
        "categoria": "laptop",
        "modelo": "Dell XPS 15",
        "precio": 1500,
        "stock": 10,
        "descripcion": "Portátil potente con pantalla de alta resolución y rendimiento excepcional para profesionales.",
    },
    {
        "categoria": "laptop",
        "modelo": "MacBook Air M2",
        "precio": 1300,
        "stock": 15,
        "descripcion": "Diseño ultradelgado, chip M2 eficiente, ideal para productividad y creatividad en movimiento.",
    },
    {
        "categoria": "laptop",
        "modelo": "HP Spectre x360",
        "precio": 1400,
        "stock": 8,
        "descripcion": "Convertible 2 en 1 con gran versatilidad y diseño elegante, perfecto para trabajo y ocio.",
    },
    {
        "categoria": "laptop",
        "modelo": "Lenovo ThinkPad X1 Carbon",
        "precio": 1600,
        "stock": 7,
        "descripcion": "Laptop empresarial duradera y ligera, con teclado legendario y excelentes características de seguridad.",
    },
    {
        "categoria": "laptop",
        "modelo": "Asus ROG Zephyrus G14",
        "precio": 1800,
        "stock": 5,
        "descripcion": "Portátil gaming compacto y potente, con excelente rendimiento para juegos y creación de contenido.",
    },
    # Monitores
    {
        "categoria": "monitor",
        "modelo": "LG UltraGear 27GP850-B",
        "precio": 450,
        "stock": 12,
        "descripcion": "Monitor gaming de 27 pulgadas, 1440p, 165Hz con tiempo de respuesta rápido y colores vibrantes.",
    },
    {
        "categoria": "monitor",
        "modelo": "Dell UltraSharp U2723QE",
        "precio": 600,
        "stock": 9,
        "descripcion": "Monitor 4K de 27 pulgadas con excelente precisión de color y conectividad USB-C, ideal para profesionales.",
    },
    {
        "categoria": "monitor",
        "modelo": "Samsung Odyssey G7",
        "precio": 700,
        "stock": 6,
        "descripcion": "Monitor curvo de 32 pulgadas, 1440p, 240Hz, diseñado para una experiencia de juego inmersiva.",
    },
    # Periféricos
    {
        "categoria": "perifericos",
        "modelo": "Logitech MX Master 3S",
        "precio": 100,
        "stock": 20,
        "descripcion": "Ratón ergonómico avanzado con desplazamiento MagSpeed, ideal para productividad y control preciso.",
    },
    {
        "categoria": "perifericos",
        "modelo": "HyperX Cloud II",
        "precio": 80,
        "stock": 25,
        "descripcion": "Auriculares gaming cómodos con sonido envolvente 7.1 y micrófono con cancelación de ruido.",
    },
]

# Variable global para almacenar la categoría predicha
predicted_image_category = None

In [22]:
import pandas as pd

df_products = pd.DataFrame(ecommerce_products)
display(df_products)

,categoria,modelo,precio,stock,descripcion
0,laptop,Dell XPS 15,1500,10,Portátil potente con pantalla de alta resoluci...
1,laptop,MacBook Air M2,1300,15,"Diseño ultradelgado, chip M2 eficiente, ideal ..."
2,laptop,HP Spectre x360,1400,8,Convertible 2 en 1 con gran versatilidad y dis...
3,laptop,Lenovo ThinkPad X1 Carbon,1600,7,"Laptop empresarial duradera y ligera, con tecl..."
4,laptop,Asus ROG Zephyrus G14,1800,5,"Portátil gaming compacto y potente, con excele..."
5,monitor,LG UltraGear 27GP850-B,450,12,"Monitor gaming de 27 pulgadas, 1440p, 165Hz co..."
6,monitor,Dell UltraSharp U2723QE,600,9,Monitor 4K de 27 pulgadas con excelente precis...
7,monitor,Samsung Odyssey G7,700,6,"Monitor curvo de 32 pulgadas, 1440p, 240Hz, di..."
8,perifericos,Logitech MX Master 3S,100,20,Ratón ergonómico avanzado con desplazamiento M...
9,perifericos,HyperX Cloud II,80,25,Auriculares gaming cómodos con sonido envolven...

### 4. Clasificación Zero-Shot de Descripciones de Productos

Vamos a utilizar un modelo de clasificación zero-shot para categorizar las descripciones de nuestros productos existentes. Esto nos permitirá asignar una categoría basada en el texto descriptivo del producto, sin necesidad de entrenar un modelo específico para este dataset.

In [23]:
from transformers import pipeline

# Inicializar el pipeline de clasificación zero-shot
# Usamos un un modelo de Hugging Face ampliamente utilizado y estable.
classifier = pipeline("zero-shot-classification", model="facebook/bart-large-mnli", device=0 if torch.cuda.is_available() else -1)

# Definir las etiquetas candidatas para la clasificación
candidate_labels = ['laptop', 'monitor', 'perifericos', 'otros']

def classify_description_zero_shot(description):
    if pd.isna(description):
        return "otros"
    # Realizar la clasificación
    result = classifier(description, candidate_labels, multi_label=False)
    # Retornar la etiqueta con la puntuación más alta
    return result['labels'][0]

# Aplicar la clasificación a la columna 'descripcion' del DataFrame
df_products['categoria_zero_shot'] = df_products['descripcion'].apply(classify_description_zero_shot)

# Mostrar el DataFrame con la nueva columna de categoría zero-shot
display(df_products)

Loading weights:   0%|          | 0/515 [00:00<?, ?it/s]

,categoria,modelo,precio,stock,descripcion,categoria_zero_shot
0,laptop,Dell XPS 15,1500,10,Portátil potente con pantalla de alta resoluci...,monitor
1,laptop,MacBook Air M2,1300,15,"Diseño ultradelgado, chip M2 eficiente, ideal ...",perifericos
2,laptop,HP Spectre x360,1400,8,Convertible 2 en 1 con gran versatilidad y dis...,perifericos
3,laptop,Lenovo ThinkPad X1 Carbon,1600,7,"Laptop empresarial duradera y ligera, con tecl...",laptop
4,laptop,Asus ROG Zephyrus G14,1800,5,"Portátil gaming compacto y potente, con excele...",laptop
5,monitor,LG UltraGear 27GP850-B,450,12,"Monitor gaming de 27 pulgadas, 1440p, 165Hz co...",monitor
6,monitor,Dell UltraSharp U2723QE,600,9,Monitor 4K de 27 pulgadas con excelente precis...,monitor
7,monitor,Samsung Odyssey G7,700,6,"Monitor curvo de 32 pulgadas, 1440p, 240Hz, di...",monitor
8,perifericos,Logitech MX Master 3S,100,20,Ratón ergonómico avanzado con desplazamiento M...,monitor
9,perifericos,HyperX Cloud II,80,25,Auriculares gaming cómodos con sonido envolven...,laptop

### 2. Módulo de Carga de Imágenes y Categorización
Este módulo permitirá al usuario subir una imagen. Un modelo de clasificación de imágenes de Hugging Face la categorizará, y el resultado se mostrará y se almacenará para el chatbot.

In [33]:
import gradio as gr
from transformers import pipeline
from PIL import Image
import torch

# Define candidate labels for zero-shot image classification with more descriptive terms
image_candidate_labels = [
    'ordenador portatil, laptop',
    'pantalla de ordenador, monitor',
    'teclados, ratones o auriculares de ordenador (perifericos)',
    'elementos no relacionados con electronica de oficina (otros)'
]

# Cargar el pipeline de clasificación de imágenes zero-shot usando un modelo CLIP
image_classifier = pipeline(
    "zero-shot-image-classification",
    model="openai/clip-vit-large-patch14", # Updated model
    device=0 if torch.cuda.is_available() else -1
)

def classify_image(image: Image.Image):
    global predicted_image_category
    if image is None:
        predicted_image_category = None
        return "Por favor, sube una imagen para categorizar."

    # Realizar la clasificación zero-shot de la imagen con las etiquetas candidatas
    predictions = image_classifier(image, candidate_labels=image_candidate_labels)

    CONFIDENCE_THRESHOLD = 0.5 # Define a confidence threshold

    top_product_label = None
    top_product_score = 0.0
    other_score = 0.0

    for pred in predictions:
        full_label = pred["label"]
        score = pred["score"]

        # Directly identify the 'otros' label based on its unique phrase
        if 'otros)' in full_label: # 'elementos no relacionados con electronica de oficina (otros)'
            other_score = score
        else: # These are potential product categories
            # Map full label to simplified product category
            simplified_label = 'unknown'
            if 'laptop' in full_label:
                simplified_label = 'laptop'
            elif 'monitor' in full_label:
                simplified_label = 'monitor'
            elif 'perifericos' in full_label:
                simplified_label = 'perifericos'

            # Keep track of the highest scoring product category
            if simplified_label != 'unknown' and score > top_product_score:
                top_product_score = score
                top_product_label = simplified_label

    # Decision logic:
    # 1. If a product category has a score above threshold AND it's higher than 'otros' score
    # 2. Else if 'otros' score is above threshold (implies 'otros' is the most confident or product scores are low)
    # 3. Else fallback to 'otros' (no strong confidence in any specific category)
    if top_product_score >= CONFIDENCE_THRESHOLD and top_product_score > other_score:
        predicted_image_category = top_product_label
    elif other_score >= CONFIDENCE_THRESHOLD:
        predicted_image_category = 'otros'
    else:
        predicted_image_category = 'otros'

    if predicted_image_category == 'otros':
        return f"La imagen ha sido categorizada como: **{predicted_image_category.capitalize()}** (No se pudo categorizar con precisión entre los productos)."
    else:
        return f"La imagen ha sido categorizada como: **{predicted_image_category.capitalize()}**."

Loading weights:   0%|          | 0/590 [00:00<?, ?it/s]

CLIPModel LOAD REPORT from: openai/clip-vit-large-patch14
Key                                  | Status     |  |
-------------------------------------+------------+--+-
vision_model.embeddings.position_ids | UNEXPECTED |  |
text_model.embeddings.position_ids   | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

### 3. Chat de Información de Productos
Esta ventana de chat interactuará con el usuario. Si el usuario pregunta por la categoría de la imagen subida, el chatbot buscará y presentará los productos relevantes de nuestra base de datos.

In [25]:
def format_products_as_table(category):
    filtered_products = [p for p in ecommerce_products if p["categoria"] == category]
    if not filtered_products:
        return "No se encontraron productos para esta categoría."

    table_header = "| Categoría | Modelo | Precio | Stock | Descripción |\n|---|---|---|---|---|\n"
    table_rows = []
    for p in filtered_products:
        table_rows.append(f"| {p['categoria'].capitalize()} | {p['modelo']} | {p['precio']}\u20ac | {p['stock']} | {p['descripcion']} |")

    return table_header + "\n".join(table_rows)

def get_product_models_for_category(category):
    """Returns a list of product model names for a given category."""
    filtered_products = [p for p in ecommerce_products if p["categoria"] == category]
    return [p["modelo"] for p in filtered_products]

def chat_response(message, history):
    global predicted_image_category # Access the global variable

    user_message_lower = message.lower()
    last_bot_message_lower = ""
    if history and history[-1][1]: # Check if there's a last bot message
        last_bot_message_lower = history[-1][1].lower()

    # Default values for product selection components (hidden and empty)
    product_choices = []
    product_selection_visible = False
    add_to_cart_visible = False

    response_text = "" # Initialize response_text

    # Scenario 1: User responded to the "Quieres consultar opciones?" prompt
    if "¿quieres consultar las opciones disponibles para la categoría?" in last_bot_message_lower:
        if any(keyword in user_message_lower for keyword in ["no", "no quiero", "gracias", "cancelar", "no me interesa"]):
            response_text = "Muy bien, puedes volver a subir otra imagen. Que tengas buen día!!!"
        elif any(keyword in user_message_lower for keyword in ["si", "sí", "quiero", "interesa", "por favor"]):
            if predicted_image_category and predicted_image_category != "No se pudo categorizar con precisión":
                product_choices = get_product_models_for_category(predicted_image_category)
                if product_choices:
                    response_text = f"Claro, aquí tienes los productos para la categoría '{predicted_image_category.capitalize()}'. Por favor, selecciona los que desees agregar al carrito a continuación:"
                    product_selection_visible = True
                    add_to_cart_visible = True
                else:
                    response_text = f"No se encontraron productos para la categoría '{predicted_image_category.capitalize()}' del producto categorizado."
            else:
                response_text = "Lo siento, no tengo una categoría de imagen reciente para consultar. Por favor, primero sube y categoriza una imagen."

        return response_text, product_choices, product_selection_visible, add_to_cart_visible

    # Scenario 2: User explicitly asks for image category info
    if "informacion" in user_message_lower and "categoria" in user_message_lower and "imagen" in user_message_lower:
        if predicted_image_category and predicted_image_category != "No se pudo categorizar con precisión":
            product_choices = get_product_models_for_category(predicted_image_category)
            if product_choices:
                response_text = f"Claro, aquí tienes los productos para la categoría '{predicted_image_category.capitalize()}'. Por favor, selecciona los que desees agregar al carrito a continuación:"
                product_selection_visible = True
                add_to_cart_visible = True
            else:
                response_text = f"No se encontraron productos para la categoría '{predicted_image_category.capitalize()}' del producto categorizado."
        else:
            response_text = "Lo siento, no tengo una categoría de imagen reciente para consultar. Por favor, primero sube y categoriza una imagen."

        return response_text, product_choices, product_selection_visible, add_to_cart_visible

    # Scenario 3: General Gemini response
    try:
        # Prepare chat history for Gemini in the required format
        gemini_history = []
        for user_msg, model_msg in history:
            if user_msg is not None:
                gemini_history.append({"role": "user", "parts": [user_msg]})
            if model_msg is not None:
                gemini_history.append({"role": "model", "parts": [model_msg]})
        gemini_history.append({"role": "user", "parts": [message]})

        response = gemini_model.generate_content(gemini_history)
        response_text = response.text
    except Exception as e:
        response_text = f"Lo siento, tuve un error al contactar a Gemini: {e}"

    return response_text, product_choices, product_selection_visible, add_to_cart_visible

### Construcción de la Interfaz Gradio
Finalmente, combinaremos los tres componentes en una interfaz de pestañas con Gradio.

### 4. Integración de Gemini para Respuestas del Chat

Vamos a integrar el modelo Gemini para que el chatbot pueda responder preguntas de forma más avanzada, utilizando conocimiento general y no solo la base de datos de productos.

Para usar la API de Gemini, necesitarás una clave API. Si aún no tienes una, crea una clave en Google AI Studio.

En Colab, añade la clave al gestor de secretos bajo el icono "🔑" en el panel izquierdo. Dale el nombre `GOOGLE_API_KEY`. Luego, pasa la clave al SDK:

In [26]:
# Importar el SDK de Python
import google.generativeai as genai
# Utilizado para almacenar de forma segura tu clave API
from google.colab import userdata

GEMINI_API_KEY=userdata.get('GEMINI_API_KEY')
genai.configure(api_key=GEMINI_API_KEY)

Ahora inicializamos el modelo Gemini.

In [27]:
# Inicializar el modelo Gemini
gemini_model = genai.GenerativeModel('gemini-2.5-flash')

Ahora, modificaremos la función `chat_response` para usar `gemini_model` para generar respuestas cuando no se trate de una consulta de categoría de imagen o un saludo.

In [28]:
def post_categorization_welcome(image_category, chat_history):
    if image_category and "No se pudo categorizar" not in image_category:
        # Extract the actual category name from the output string
        # Assuming image_category is formatted like: "La imagen ha sido categorizada como: **Laptop** (Predicción original: ...)"
        try:
            category_name = image_category.split('**')[1].split('**')[0]
        except IndexError:
            category_name = "la categoría de la imagen"

        welcome_message = f"Hola! La imagen subida corresponde a {category_name}. \u00bfQuieres consultar las opciones disponibles para la categoría?"
        return chat_history + [[None, welcome_message]] # Add a bot message directly
    return chat_history

In [29]:
import gradio as gr

with gr.Blocks(title="App de E-commerce con IA") as demo:
    gr.Markdown("# App de E-commerce con IA")

    # Módulo de Categorización de Imágenes
    with gr.Column(elem_id="image_categorization_section"):
        gr.Markdown("## Módulo de Categorización de Imágenes")
        gr.Markdown("Sube una imagen de un producto (laptop, monitor o periférico) para que sea categorizada por un modelo de IA.")
        image_input = gr.Image(type="pil", label="Sube una imagen de un producto")
        image_output = gr.Textbox(label="Categoría Predicha")
        categorize_button = gr.Button("Categorizar Imagen")
        clear_image_button = gr.Button("Subir una nueva imagen")
        consult_options_button = gr.Button("Consultar opciones disponibles")

        # Function to clear image inputs and reset category
        def clear_image_inputs():
            global predicted_image_category
            predicted_image_category = None
            return None, "" # Clear image_input and image_output

        # Define the action for the categorize button
        categorize_button.click(classify_image, inputs=image_input, outputs=image_output)

        # Link new buttons
        clear_image_button.click(clear_image_inputs, outputs=[image_input, image_output])

    gr.Markdown("--- # --- # --- # ---") # Separador

    # Asistente de Información de Productos (Chat Interface)
    with gr.Column(elem_id="chat_section"):
        gr.Markdown("## Asistente de Información de Productos")
        gr.Markdown("Pregúntame si quieres información sobre la categoría de la última imagen subida (por ejemplo: 'Quiero información sobre la categoría de la imagen').")

        # Now define chatbot here so it's rendered in this section
        chatbot = gr.Chatbot(height=300)

        msg = gr.Textbox(placeholder="Pregúntame sobre la categoría de la imagen subida o sobre los productos.", container=False, scale=7)
        submit_btn = gr.Button("Enviar")

        # Product selection components, initially hidden
        product_selection_checkboxes = gr.CheckboxGroup([], label="Selecciona productos para agregar al carrito", visible=False)
        add_to_cart_btn = gr.Button("Agregar producto(s) seleccionado(s) al carrito", visible=False)

        # Function to handle user message and update chat history for Gradio Blocks
        def user_message_handler(user_message, chat_history):
            # Hide product selection when new message is sent
            return "", chat_history + [[user_message, None]], gr.update(visible=False), gr.update(visible=False)

        # Function to generate bot response and update chat history, including product selection
        def bot_response_wrapper(chat_history):
            if chat_history:
                user_message = chat_history[-1][0] # Get the latest user message
                # chat_response now returns (response_text, product_choices, product_selection_visible, add_to_cart_visible)
                response_text, product_choices, product_selection_visible, add_to_cart_visible = chat_response(user_message, chat_history[:-1])
                chat_history[-1][1] = response_text # Update the latest bot response

            return (
                chat_history,
                gr.update(choices=product_choices, visible=product_selection_visible),
                gr.update(visible=add_to_cart_visible)
            )

        # Function to generate the initial welcome message for the chat
        def post_categorization_welcome(image_category, chat_history):
            if image_category and "No se pudo categorizar" not in image_category:
                category_name = image_category.split('**')[1].split('**')[0]
                welcome_message = f"Hola! La imagen subida corresponde a la categoría \"{category_name}\". \u00bfQuieres consultar las opciones disponibles para la categoría?"
                # This function now needs to return updates for product selection too, but it's only for the initial welcome, so no products yet
                return chat_history + [[None, welcome_message]]
            return chat_history

        # Link the message input and submit button to the chat logic
        msg.submit(user_message_handler, [msg, chatbot], [msg, chatbot, product_selection_checkboxes, add_to_cart_btn], queue=False).then(
            bot_response_wrapper,
            inputs=[chatbot],
            outputs=[chatbot, product_selection_checkboxes, add_to_cart_btn]
        )
        submit_btn.click(user_message_handler, [msg, chatbot], [msg, chatbot, product_selection_checkboxes, add_to_cart_btn], queue=False).then(
            bot_response_wrapper,
            inputs=[chatbot],
            outputs=[chatbot, product_selection_checkboxes, add_to_cart_btn]
        )

        # New handler for the 'Add to Cart' button
        def add_selected_products_to_cart(selected_products, chat_history):
            if not selected_products:
                bot_message = "No has seleccionado ningún producto para agregar al carrito."
            else:
                # Simulate adding to cart - in a real app, this would update a database or session
                cart_items_str = ", ".join(selected_products)
                bot_message = f"¡Perfecto! Se han agregado los siguientes productos al carrito: {cart_items_str}. ¿Hay algo más en lo que pueda ayudarte?"

            chat_history.append([None, bot_message])
            return (
                chat_history,
                gr.update(choices=[], visible=False), # Hide and clear checkboxes
                gr.update(visible=False) # Hide button
            )

        add_to_cart_btn.click(
            add_selected_products_to_cart,
            inputs=[product_selection_checkboxes, chatbot],
            outputs=[chatbot, product_selection_checkboxes, add_to_cart_btn]
        )

    # Move consult_options_button here so it's after the chat_section but still within the Blocks
    # This button needs access to chatbot, so chatbot must be defined before this line.
    with gr.Row(): # Use a Row to group these buttons if you want them on the same line
        # consult_options_button.render() # Removed this line as it causes DuplicateBlockError
        consult_options_button.click(
            post_categorization_welcome,
            inputs=[image_output, chatbot], # image_output for the category, chatbot for history
            outputs=chatbot # Update the chatbot component
        )

demo.launch(share=True)

Colab notebook detected. To show errors in colab notebook, set debug=True in launch()
IMPORTANT: You are using gradio version 3.50.2, however version 4.44.1 is available, please upgrade.
--------
Running on public URL: https://d1bc3767de65ccb62d.gradio.live

This share link expires in 72 hours. For free permanent hosting and GPU upgrades, run `gradio deploy` from Terminal to deploy to Spaces (https://huggingface.co/spaces)

In [30]:
import gradio
print(gradio.__version__)

3.50.2